name: Refresh Go Cache

on:
  push:
    branches:
      - main
    paths:
      - go.work
      - "**/go.mod"
      - "**/versions.go"
      - .github/workflows/refresh-go-cache.yaml
  workflow_dispatch:

jobs:
  refresh:
    uses: curioswitch/go-build/.github/workflows/export-refresh-go-cache.yaml@f60fc8379d735d0415c0c56339d389f680760d96 # v0.6.3
